apiVersion: v1
kind: Namespace
metadata:
  name: shinyproxy1-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shinyproxy-operator-sa-role
  namespace: shinyproxy1-app
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shinyproxy-sa-role
  namespace: shinyproxy1-app
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy-operator-sa-rolebinding
  namespace: shinyproxy1-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shinyproxy-operator-sa-role
subjects:
- kind: ServiceAccount
  name: shinyproxy-operator-sa
  namespace: shinyproxy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy-sa-rolebinding
  namespace: shinyproxy1-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shinyproxy-sa-role
subjects:
- kind: ServiceAccount
  name: shinyproxy-sa
  namespace: shinyproxy-operator
